workflows:
  ios_smoke:
    name: iOS Smoke (no signing)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build IPA (no codesign)
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache
        - ios/Pods

  ios_release:
    name: iOS Release (Signed + TestFlight)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: zenyourself-zenyourself
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Update CocoaPods
        script: pod repo update
      - name: Automatic code signing (fetch & apply)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --api-key "$APP_STORE_CONNECT_PRIVATE_KEY" --create
          keychain add-certificates
          xcode-project use-profiles --path ios/Runner.xcodeproj
      - name: Build signed IPA (release)
        script: |
          flutter build ipa --release --no-tree-shake-icons \
            --build-name=$CM_BUILD_NUMBER --build-number=$CM_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache
        - ios/Pods
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
