name: zenyourself
description: ZenYourself App mit Sprach-Input und GPT-Antwort
publish_to: "none"
version: 1.0.0+1

# Dart/Flutter Basis – passt zu Flutter ≥3.19 (Dart 3.3)
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---- State / DI -----------------------------------------------------
  provider: ^6.1.5
  characters: ^1.3.0
  meta: ^1.12.0

  # ---- System / Storage ----------------------------------------------
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # ---- Networking / JSON ---------------------------------------------
  http: ^1.4.0
  json_annotation: ^4.9.0

  # ---- UI / UX --------------------------------------------------------
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  lottie: ^3.3.1
  animations: ^2.0.11
  fl_chart: ^1.0.0

  # ---- Media / Audio --------------------------------------------------
  just_audio: ^0.9.36

  # ---- Device / Permissions / Notifications --------------------------
  permission_handler: ^11.3.0
  flutter_local_notifications: ^19.0.0    # Falls dein Flutter älter ist, ggf. auf ^17.x pinnen (siehe Kommentar unten)

  # ---- Utilities ------------------------------------------------------
  url_launcher: ^6.3.0                   # <— für tel: und https:, nötig für CH-Hotlines
  share_plus: ^11.0.0                    # Bei sehr alter Flutter-SDK ggf. ^10.0.2 verwenden
  speech_to_text: ^7.2.0
  flutter_dotenv: ^5.0.2
  screenshot: ^3.0.0
  uuid: ^4.4.2
  collection: ^1.18.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0

  # ---- App-Icon Generator --------------------------------------------
  flutter_launcher_icons: ^0.13.1

# OPTIONAL: Falls der Pub-Solver wegen älterer Flutter-Channel-Versionen streikt,
# kannst du temporär pins setzen (eine von beiden Zeilen auskommentieren/aktivieren):
# dependency_overrides:
#   share_plus: ^10.0.2
#   flutter_local_notifications: ^17.2.0

# App-Icons (Pro: adaptive + monochrome + iOS Alpha-Removal)
flutter_launcher_icons:
  android: true
  ios: true
  # Basis-Icon (mind. 1024x1024, ohne abgerundete Ecken)
  image_path: assets/icons/icon_zenyourself.png
  # Adaptive Icons (Android 8.0+)
  adaptive_icon_background: "#2F5F49"               # Zen-Grün (oder PNG)
  adaptive_icon_foreground: assets/icons/icon_zenyourself.png
  adaptive_icon_monochrome: assets/icons/icon_zenyourself.png
  # Platform Tweaks
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/journey_rain.png
    - assets/schoen.png
    - assets/schmetterlingpanda.png
    - assets/reflektionpanda.png
    - assets/zen_background.png
    - assets/logo.png
    - assets/zen_pattern.png
    - assets/reflektionpanda2.png
    - assets/pandalaterne2.png
    - assets/pandalaterne.png
    - assets/megaschön.png
    - assets/langerweg.png
    - assets/flusspanda.png
    - assets/brueckenpanda.png
    - assets/pandasitz.png
    - assets/startbild1.png
    - assets/startbild2.png
    - assets/startbild3.png
    - assets/startbild4.png
    - assets/startbild5.png
    - assets/startbild6.png
    - assets/panda.png
    - assets/logo_zenyourself.png
    - assets/zen_garden.png
    - assets/zen_journey_bg.png
    - assets/startscreen1.png
    - assets/reflekt.png
    - assets/voice_panda.png
    - assets/pro_screen.png
    - assets/butterfly_left.png
    - assets/butterfly_right.png
    - assets/butterfly_center.png
    - assets/paper_texture.png
    - assets/teich.png
    - assets/tempel.png
    - assets/welcomescreen.png
    - assets/woleknhimmel.png   # Schreibweise prüfen – falls Datei 'wolkenhimmel.png' heißt, hier anpassen
    - assets/wolken.png
    - assets/zweiwege.png
    - assets/panda-header.png
    - assets/story_panda_final.png
    - assets/bg/bg_start.png
    - assets/bg/bg_journal.png
    - assets/bg/bg_menu.png
    - assets/bg/bg_reflection.png
    - assets/star_pa.png

    # Ordner komplett:
    - assets/audio/
    - assets/panda_moods/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

    # ZenKalligrafie vorläufig auf NotoSans aliasiert, damit der Build nie
    # an einer fehlenden Datei scheitert. Wenn vorhanden, ersetze den Pfad
    # durch assets/fonts/ZenKalligrafie-Regular.ttf
    - family: ZenKalligrafie
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
