buildscript {
    ext.kotlin_version = '1.8.22' // darf so bleiben, später gern auf 2.x anheben
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // WICHTIG: AGP 8.6.x – unterstützt 16 KB + compileSdk 35
        classpath 'com.android.tools.build:gradle:8.6.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
